image: Visual Studio 2022

environment:
  DOTNET_VERSION: 8.0.100

install:
  - cmd: echo "Using .NET version %DOTNET_VERSION%"
  - cmd: choco upgrade dotnet-sdk -y

build_script:
  - cmd: echo "Current Directory: %cd%"  # Print the current working directory
  - cmd: dotnet --version  # Ensure we're using .NET 8
  - cmd: dotnet restore "NameSortingApp.sln"  # Use relative path to solution file
  - cmd: dotnet build "NameSortingApp.sln" --configuration Release
  - cmd: dotnet test "NameSortingApp.sln"