image: Visual Studio 2022  # Ensures the latest SDK is available

environment:
  DOTNET_VERSION: 8.0.100  # Set desired .NET version

test_script:
  - dotnet test --no-build --logger "console;verbosity=detailed"

build_script:
  - cmd: dotnet --version  # Ensure we're using .NET 8
  - cmd: dotnet build "NameSortingApp.sln" --configuration Release
  - cmd: dotnet test "NameSortingApp.sln"s
  - cmd: mkdir release
  - cmd: copy bin\Release\net8.0\NameSortingApp.exe release\
  - cmd: copy bin\Release\net8.0\NameSortingApp.dll release\
  - cmd: copy bin\Release\net8.0\NameSortingApp.runtimeconfig.json release\
  - cmd: copy README.md release\
  

artifacts:   # Artifacts (Specify what files to deploy)
  - path: release\*
    name: NameSortingApp

# Deployment Configuration (e.g., GitHub Releases, FTP, or S3)
deploy:
  - provider: GitHub
    auth_token:
      secure: mIBEb8iOMalCmZHKVnSuTx3jPuY9IIjRIJoRXjypEIvF25dXs2E+6P/Df5f8106d
    artifact: release\*
    tag: v1.0.{build}
    release: NameSortingApp Release v1.0.{build}
    draft: false
    prerelease: false