image: Visual Studio 2022  # Ensures the latest SDK is available

environment:
  DOTNET_VERSION: 8.0.100  # Set desired .NET version

test_script:
  - dotnet test --no-build --logger "console;verbosity=detailed"

build_script:
  - cmd: dotnet --version  # Ensure we're using .NET 8
  - cmd: dotnet build "NameSortingApp.sln" --configuration Release
  - cmd: dotnet test "NameSortingApp.sln"