image: Visual Studio 2022  # Ensures the latest SDK is available

environment:
  DOTNET_VERSION: 8.0.100

install:
  - cmd: echo "Using .NET version %DOTNET_VERSION%"
  - cmd: choco upgrade dotnet-sdk -y
  - cmd: dotnet --list-sdks
  
build_script:
  - cmd: dotnet --version  # Ensure we're using .NET 8
  - cmd: dotnet restore
  - cmd: dotnet build --configuration Release
  - cmd: dotnet test