image: Visual Studio 2022  # Ensures the latest SDK is available

environment:
  DOTNET_VERSION: 8.0.100  # Set desired .NET version

test_script:
  - dotnet test --no-build --logger "console;verbosity=detailed"

build_script:
  - cmd: dotnet --version  # Ensure we're using .NET 8
  - cmd: dotnet build "NameSortingApp.sln" --configuration Release
  - cmd: dotnet test "NameSortingApp.sln"
  

artifacts:   # Artifacts (Specify what files to deploy)
  - path: bin\Release\net8.0\*
    name: NameSortingApp

# Deployment Configuration (e.g., GitHub Releases, FTP, or S3)
deploy:
  - provider: GitHub
    auth_token:
      secure: mIBEb8iOMalCmZHKVnSuTx3jPuY9IIjRIJoRXjypEIvF25dXs2E+6P/Df5f8106d
    artifact: /.*\.exe/
    tag: v1.1.{build}
    release: NameSortingApp Release v1.1.{build}
    draft: false
    prerelease: false