# Define build environment
image: Visual Studio 2022  # Use Windows with VS 2022

environment:
  DOTNET_VERSION: 8.0.x  # Specify .NET 8

install:
  - ps: Install-Module -Name PowerShellGet -Force -SkipPublisherCheck
  - ps: Install-Module -Name NuGet -Force -SkipPublisherCheck
  - ps: choco install dotnet-sdk --version=8.0.100 -y
  - ps: refreshenv 

build_script:
  - cmd: dotnet --version  # Check installed .NET version
  - cmd: dotnet restore
  - cmd: dotnet build --configuration Release
  - cmd: dotnet test